name:                mssql-simple
version:             0.6.0.5
github:              "mitsuji/mssql-simple"
license:             BSD3
author:              "Takamasa Mitsuji"
maintainer:          "tkms@mitsuji.org"
copyright:           "2019 Takamasa Mitsuji"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            SQL Server client library implemented in Haskell
category:            Database

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mitsuji/mssql-simple#readme>

dependencies:
- base >= 4.7 && < 5
- ms-tds >= 0.4 && < 0.5
- bytestring
- binary
- text
- time
- network
- hostname
- tls
- template-haskell
- mtl
- transformers
- uuid-types


library:
  source-dirs: src


tests:
  tds-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mssql-simple
